# Generated by Django 2.2.2 on 2020-06-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
